import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useUserProfile } from '@/hooks/useUserProfile';
import { FnShiftType } from '@/types/financialNavigator';

export interface FnRecurrenceRule {
  id: string;
  user_id: string;
  service_id: string;
  shift_type: FnShiftType;
  weekday: number;        // 0=Dom … 6=Sáb
  frequency: 'weekly' | 'biweekly';
  start_month: string;    // 'YYYY-MM'
  end_month: string;      // 'YYYY-MM'
  is_active: boolean;
  created_at?: string;
}

const KEY = (uid: string) => ['fn_recurrence_rules', uid];

const WEEKDAY_LABELS = ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'];
const FREQ_LABELS: Record<string, string> = { weekly: 'Semanal', biweekly: 'Quinzenal' };

export { WEEKDAY_LABELS, FREQ_LABELS };

export function useFnRecurrence() {
  const { profile } = useUserProfile();
  const uid = profile?.user_id ?? '';
  const qc = useQueryClient();

  const { data: rules = [], isLoading } = useQuery({
    queryKey: KEY(uid),
    enabled: !!uid,
    queryFn: async (): Promise<FnRecurrenceRule[]> => {
      const { data, error } = await (supabase as any)
        .from('fn_recurrence_rules')
        .select('*')
        .eq('user_id', uid)
        .order('created_at');
      if (error) throw error;
      return data as FnRecurrenceRule[];
    },
  });

  const invalidate = () => qc.invalidateQueries({ queryKey: KEY(uid) });

  const upsertRule = useMutation({
    mutationFn: async (rule: Partial<FnRecurrenceRule> & { service_id: string }) => {
      if (rule.id) {
        const { error } = await (supabase as any)
          .from('fn_recurrence_rules')
          .update({ ...rule, updated_at: new Date().toISOString() })
          .eq('id', rule.id)
          .eq('user_id', uid);
        if (error) throw error;
      } else {
        const { error } = await (supabase as any)
          .from('fn_recurrence_rules')
          .insert({ ...rule, user_id: uid });
        if (error) throw error;
      }
    },
    onSuccess: invalidate,
  });

  const deleteRule = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await (supabase as any)
        .from('fn_recurrence_rules')
        .delete()
        .eq('id', id)
        .eq('user_id', uid);
      if (error) throw error;
    },
    onSuccess: invalidate,
  });

  /** Generate all dates for a recurrence rule */
  const expandRuleDates = (rule: FnRecurrenceRule): string[] => {
    const dates: string[] = [];
    const [sy, sm] = rule.start_month.split('-').map(Number);
    const [ey, em] = rule.end_month.split('-').map(Number);
    const startDate = new Date(sy, sm - 1, 1);
    const endDate = new Date(ey, em, 0); // last day of end month

    let current = new Date(startDate);
    // Find first matching weekday
    while (current.getDay() !== rule.weekday && current <= endDate) {
      current.setDate(current.getDate() + 1);
    }

    const step = rule.frequency === 'biweekly' ? 14 : 7;
    while (current <= endDate) {
      const ds = `${current.getFullYear()}-${String(current.getMonth() + 1).padStart(2, '0')}-${String(current.getDate()).padStart(2, '0')}`;
      dates.push(ds);
      current.setDate(current.getDate() + step);
    }
    return dates;
  };

  /** Project shifts from a single rule into fn_calendar_shifts */
  const projectRule = useMutation({
    mutationFn: async (rule: FnRecurrenceRule) => {
      const dates = expandRuleDates(rule);
      if (dates.length === 0) return;

      const rows = dates.map(d => ({
        user_id: uid,
        service_id: rule.service_id,
        shift_date: d,
        shift_type: rule.shift_type,
        status: 'projetado',
      }));

      // Delete existing projected shifts for this rule's parameters first
      for (const d of dates) {
        await (supabase as any)
          .from('fn_calendar_shifts')
          .delete()
          .eq('user_id', uid)
          .eq('service_id', rule.service_id)
          .eq('shift_date', d)
          .eq('shift_type', rule.shift_type)
          .eq('status', 'projetado');
      }

      const { error } = await (supabase as any).from('fn_calendar_shifts').insert(rows);
      if (error) throw error;
    },
    onSuccess: () => {
      invalidate();
      qc.invalidateQueries({ queryKey: ['fn_calendar_shifts', uid] });
    },
  });

  /** Remove all projected shifts generated by a rule */
  const removeProjectedShifts = useMutation({
    mutationFn: async (rule: FnRecurrenceRule) => {
      const dates = expandRuleDates(rule);
      for (const d of dates) {
        await (supabase as any)
          .from('fn_calendar_shifts')
          .delete()
          .eq('user_id', uid)
          .eq('service_id', rule.service_id)
          .eq('shift_date', d)
          .eq('shift_type', rule.shift_type)
          .eq('status', 'projetado');
      }
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['fn_calendar_shifts', uid] });
    },
  });

  const getRulesForService = (serviceId: string) =>
    rules.filter(r => r.service_id === serviceId);

  return {
    rules,
    isLoading,
    upsertRule,
    deleteRule,
    projectRule,
    removeProjectedShifts,
    expandRuleDates,
    getRulesForService,
  };
}
