// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emxgbizhkhujyoyyfpxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVteGdiaXpoa2h1anlveXlmcHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTQ4NTUsImV4cCI6MjA2OTQ3MDg1NX0.ursNVsuWN-T2_YsJ1yypqpKyLMZgtzyKhpLanD11SrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});